# Generated by Django 4.1.6 on 2024-06-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
