# Generated by Django 4.1.6 on 2024-06-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_title'),
        ('orders', '0008_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reports', to='store.product'),
        ),
    ]
