# Generated by Django 4.1.6 on 2024-06-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_inventoryreport_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
