# Generated by Django 4.1.6 on 2024-06-18 08:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
