# Generated by Django 4.1.6 on 2024-06-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_salesreport_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryreport',
            options={'ordering': ('-created',)},
        ),
    ]
