# Generated by Django 4.1.6 on 2024-06-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_inventoryreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
