# Generated by Django 4.1.6 on 2026-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_secondaryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
