# Generated by Django 4.1.6 on 2026-09-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_inventorymovement_remaining_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='previous_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
